version: '3'

services:
  theater-api:
    build: .
    container_name: theater-api
    restart: always
    volumes:
      - .:/theater-api-api
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5438:5432

volumes:
  postgres_data: