"""init migrations

Revision ID: c53763444cb5
Revises: 
Create Date: 2020-12-20 19:32:49.070632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c53763444cb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('patronymic', sa.VARCHAR(length=100), nullable=False),
    sa.Column('rank', sa.VARCHAR(length=100), nullable=False),
    sa.Column('experience', sa.VARCHAR(length=100), nullable=False),
    sa.Column('achievements', sa.VARCHAR(length=100), nullable=False),
    sa.Column('balance', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATE(), nullable=True),
    sa.Column('updated_at', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performances',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('year_of_production', sa.DATE(), nullable=False),
    sa.Column('budget', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=True),
    sa.Column('updated_at', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premium_configs',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('performance_num', sa.SMALLINT(), nullable=False),
    sa.Column('prize', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=True),
    sa.Column('updated_at', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actors_employments',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('actor_id', sa.BIGINT(), nullable=False),
    sa.Column('performance_id', sa.BIGINT(), nullable=False),
    sa.Column('role_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=True),
    sa.Column('updated_at', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('term', sa.VARCHAR(length=100), nullable=False),
    sa.Column('actor_id', sa.BIGINT(), nullable=False),
    sa.Column('salary_per_year', sa.FLOAT(), nullable=False),
    sa.Column('min_premium_amount', sa.SMALLINT(), nullable=False),
    sa.Column('sign_date', sa.DATE(), nullable=True),
    sa.Column('expiration_date', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DATE(), nullable=True),
    sa.Column('updated_at', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    op.drop_table('actors_employments')
    op.drop_table('roles')
    op.drop_table('premium_configs')
    op.drop_table('performances')
    op.drop_table('actors')
    # ### end Alembic commands ###
